"""add today_update column

Revision ID: 9a3bbdcf52da
Revises: '8bb3e56ff80e'
Create Date: 2026-06-30 22:00:52.906816

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3bbdcf52da'
down_revision: Union[str, None] = '8bb3e56ff80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_projects', sa.Column('today_update', sa.Text(), nullable=True))
    op.add_column('project_tasks', sa.Column('task_type', sa.String(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tasks', 'task_type')
    op.drop_column('client_projects', 'today_update')
    # ### end Alembic commands ###
